### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by tbsvttr** [tbsvttr/install-ruby-and-rails#1]
Someone needs to test if this is guide is working and understandable. Could you help me @LMStudent?

**Comment by suchja** [comment]
@tbsvttr I'm not that into ruby and rails development. Just reviewed (not tested!) the OS X section. Looks good and understandable. Would it make sense to mark the steps regarding `rbenv` as optional? 
From what I know about ruby is that `rbenv` is required to install different versions of ruby. Maybe this is not always required?

In general this is a really nice guide!

**Comment by tbsvttr** [comment]
@suchja Thanks a lot. rbenv does not only helps you having multible instances of Ruby installed on your OS, but also automates the build process of Ruby. In the case of OS X having multible versions of Ruby is especially important, because you do not want to touch the preinstalled, custom Ruby by Apple. Apart from that one always should be able to create clean environments of a certian Ruby version for Ruby / Rails development due to complex dependecies of gems and usage of different Ruby or Rails versions.

**Comment by suchja** [comment]
That makes sense.
